%Выводит график переходного процесса, 2 кнопки и pop-up menu
var = 15;

%Создаём окно
delete(gcf);
figure1 = figure();

%Задаём график h(t)
T=var/100;
k=10;
t=0:0.1:10;
h=k*(1-exp(-t/T));

%Отображаем график
graph = drawPlot(t,h,figure1,mod(var,4),getColor(mod(var,6)),getColor(8));

%Создаём кнопку 1
command11=['set(graph,''Color'',getColor(mod(var,8)));',...
    'set(popup,''String'',values2);',...
    'popup_menu_Callback(popup,0);',...
    'set(button1,''CallBack'',command12);'];
command12=['set(graph,''Color'',getColor(8));',...
    'set(popup,''String'',values1);',...
    'popup_menu_Callback(popup,0);',...
    'set(button1,''CallBack'',command11);'];
button1 = uicontrol(figure1,'Style','push','Units','normalized','Position',...
    getObjectPosition(mod(var,3),0),'String','КН 1','CallBack',command11);

%Создаём кнопку 2
command21=['set(get(graph,''Parent''),''Position''',...
    ',getObjectPosition(mod(var+1,4),1));',...
    'set(popup,''Position''',',getObjectPosition(mod(var,4),1));',...
    'set(button2,''CallBack'',command22);'];
command22=['set(get(graph,''Parent''),''Position''',...
    ',getObjectPosition(mod(var,4),1));',...
    'set(popup,''Position''',',getObjectPosition(mod(var+1,4),1));',...
    'set(button2,''CallBack'',command21);'];
button2 = uicontrol(figure1,'Style','push','Units','normalized','Position',...
    getObjectPosition(mod(var,3)+1,0),'String','Кнопка 2','CallBack',command21);

%Создаём pop-up menu
values1 = {'Синий','Зелёный','Красный','Голубой','Коричневый','Серый',...
    'Фиолетовый','Розовый'};
values2 = {'Синий','Зелёный','Красный','Голубой','Коричневый','Серый',...
    'Фиолетовый','Белый'};
popup = uicontrol(figure1,'Style','popupmenu','Units','normalized',...
    'Position',getObjectPosition(mod(var+1,4),1),'String',values1,...
    'Value',mod(var,6)+1,'Callback',{@popup_menu_Callback});