%Анализ САУ y''' + a1*y'' + a2*y' + a3*y = b*u

function prog5(action)
%При первом вызове nargin == 0
if nargin < 1,
    %Создаём figure во весь экран
    bgcolor = [0.8 0.8 0.8];
    figure('Position',get(0,'ScreenSize'),'Resize','off','Color',bgcolor);

    %Задаём начальные значения
    a1 = 2; 
    a2 = 4;
    a3 = 5;
    b = 5;
    
    %Схема
    subplot(2,2,2)
    [I,map,alpha] = imread('sheme.png','png');
    img = imshow(I,map);
    set(img,'AlphaData',alpha);
    %Нулевая позиция схемы
    sp = get(get(img,'Parent'),'Position');
    %Формула
    uicontrol('Style','text','Units','normalized','BackgroundColor',...
        bgcolor,'Position',[sp(1)+0.05 sp(2)+0.3 0.3 0.05],...
        'String','y'''''' + a1*y'''' + a2*y'' + a3*y = b*u','FontSize',16);
    %a1 a2 a3 b контроллеры на схеме
    bEditor2 = uicontrol('Style','edit','Units','normalized',...
        'BackgroundColor', bgcolor,'Position',...
        [sp(1)+0.03 sp(2)+0.245 0.03 0.03],...
        'String',num2str(b),'FontSize',16,'CallBack',...
        'valueChange(''b'',2); prog5(''redraw'');');
    a1Editor2 = uicontrol('Style','edit','Units','normalized',...
        'BackgroundColor', bgcolor,'Position',...
        [sp(1)+0.26 sp(2)+0.1 0.03 0.03],...
        'String',num2str(a1),'FontSize',16,'CallBack',...
        'valueChange(''a1'',2); prog5(''redraw'');');
    a2Editor2 = uicontrol('Style','edit','Units','normalized',...
        'BackgroundColor', bgcolor,'Position',...
        [sp(1)+0.19 sp(2)+0.06 0.03 0.03],...
        'String',num2str(a2),'FontSize',16,'CallBack',...
        'valueChange(''a2'',2); prog5(''redraw'');');
    a3Editor2 = uicontrol('Style','edit','Units','normalized',...
        'BackgroundColor', bgcolor,'Position',...
        [sp(1)+0.07 sp(2)+0.01 0.03 0.03],...
        'String',num2str(a3),'FontSize',16,'CallBack',...
        'valueChange(''a3'',2); prog5(''redraw'');');
    
    %Нулевая позиция слайдеров
    sp = [0.5 0.05 0.05 0.05];
    %a1 контроллеры
    uicontrol('Style','text','Units','normalized','BackgroundColor',...
        bgcolor,'Position',[sp(1) sp(2)+0.35 0.05 sp(4)],...
        'String','a1 = ','FontSize',16);
    a1Editor = uicontrol('Style','edit','Units','normalized',...
        'Position',[sp(1)+0.1 sp(2)+0.35 sp(3) sp(4)],'FontSize',16,...
        'String',num2str(a1),'CallBack',...
        'valueChange(''a1'',1); prog5(''redraw'');');
    a1Slider = uicontrol('Style','slider','Units','normalized',...
        'Position',[sp(1) sp(2)+0.31 0.4 sp(4)-0.02],...
        'Value',a1,'Max',10,'Min',-10,...
        'CallBack','valueChange(''a1'',3); prog5(''redraw'');');
    %a2 контроллеры
    uicontrol('Style','text','Units','normalized','BackgroundColor',...
        bgcolor,'Position',[sp(1) sp(2)+0.25 0.05 sp(4)],...
        'String','a2 = ','FontSize',16);
    a2Editor = uicontrol('Style','edit','Units','normalized',...
        'Position',[sp(1)+0.1 sp(2)+0.25 sp(3) sp(4)],'FontSize',16,...
        'String',num2str(a2),'CallBack',...
        'valueChange(''a2'',1); prog5(''redraw'');');
    a2Slider = uicontrol('Style','slider','Units','normalized',...
        'Position',[sp(1) sp(2)+0.21 0.4 sp(4)-0.02],...
        'Value',a2,'Max',10,'Min',-10,...
        'CallBack','valueChange(''a2'',3); prog5(''redraw'');');
    %a3 контроллеры
    uicontrol('Style','text','Units','normalized','BackgroundColor',...
        bgcolor,'Position',[sp(1) sp(2)+0.15 0.05 sp(4)],...
        'String','a3 = ','FontSize',16);
    a3Editor = uicontrol('Style','text','Units','normalized',...
        'BackgroundColor',bgcolor,'Position',...
        [sp(1)+0.1 sp(2)+0.15 sp(3) sp(4)],'FontSize',16,...
        'String',num2str(a3));
    a3Slider = uicontrol('Style','slider','Units','normalized',...
        'Position',[sp(1) sp(2)+0.11 0.4 sp(4)-0.02],...
        'Value',a3,'Max',10,'Min',-10,...
        'CallBack','valueChange(''a3'',3); prog5(''redraw'');');
    %b контроллеры
    uicontrol('Style','text','Units','normalized','BackgroundColor',...
        bgcolor,'Position',[sp(1) sp(2)+0.05 0.05 sp(4)],...
        'String','b = ','FontSize',16);
    bEditor = uicontrol('Style','edit','Units','normalized',...
        'Position',[sp(1)+0.1 sp(2)+0.05 sp(3) sp(4)],'FontSize',16,...
        'String',num2str(b),'CallBack',...
        'valueChange(''b'',1); prog5(''redraw'');');
    
    saveValues('all',[a1 a2 a3 b...
        a1Editor a1Editor2 a1Slider a2Editor a2Editor2 a2Slider...
        a3Editor a3Editor2 a3Slider bEditor bEditor2 0]);
end

%Считаем переходную функцию
args = get(gcf,'UserData');
w = tf(args(4), [1 args(1) args(2) args(3)]);

%Перерисовываем графики
subplot(2,2,3);
step(w)
subplot(2,2,1);
nyquist(w);